### ISSUE TITLE
`onboard` returns current state

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/assist#111]
I think it would be better if calls to `onboard` would resolve and reject with the current state instead of a success or error string like it does currently. A dev could get access to all the information they need (account address etc) without needing an additional async call to `getState`. The state would still inform the dev of whether the onboarding was successful and what stage the user got up to, but in a more structured way.

**Comment by liamaharon** [comment]
@cmeisl is this enough of an API change to require a major version bump? or should it be OK to include it as a minor bump?
