### ISSUE TITLE
Should be able to specify which tx-status events produce a notification

### ISSUE THREAD

**Issue by morelazers** [blocknative/assist#115]
e.g. sometimes I don't want to show the user txSent

**Comment by cmeisl** [comment]
@aaronbarnardsound can this be handled via the new callback feature for notifications, e.g. dapp can add callback to absorb txSent event and therefore prevent notification UI? Would be good to avoid even more config options to specifically suppress a class of notifications. Also, dapp may only want to suppress based on specific tx params. The callback feature gives maximum flexibility.
