### ISSUE TITLE
Resizing window should resize the backdrop

### ISSUE THREAD

**Issue by marsrobertson** [blocknative/assist#129]
![ScreenFlow 2019-04-30 16_49_08](https://user-images.githubusercontent.com/44369284/56975085-fb187b80-6b67-11e9-97fb-efca5b21f388.gif)

**Comment by liamaharon** [comment]
Thanks @marsrobertson!

**Comment by cmeisl** [comment]
@marsrobertson thanks for catching this bug!

**Comment by marsrobertson** [comment]
You were super quick!

That was spotted in the first 2 minutes from injecting the integration...
