### ISSUE TITLE
Onboarding when on a wrong network - cannot instantiate or decorate the contract

### ISSUE THREAD

**Issue by marsrobertson** [blocknative/assist#154]
https://account.blocknative.com/api-docs

```
To integrate Assist.js into your dapp, you'll need to do 5 things:

1. Create a free account and get an API key from account.blocknative.com
2. Install the widget
3. Initialize the library
4. Call onboard
5. Decorate your contracts
```

### Here is my situation: https://youtu.be/vtGCysMnR9U

1. `1. 2. 3.` done
2. do I really want to onboard ASAP?
3. cannot instantiate contract _(I'm on a wrong network)_

I'd rather onboard only when sending a transaction, initially OK to display data without onboarding?

### Workarounds

* onboard ASAP
* `gotofail()`my own wrong network error handling

**EDIT/UPDATE:** I still need to think through about the ideal flow, will sleep on it.

### The code

```
(async function main() {
    var bncAssistConfig = {
        dappId: "_____-_______-________-_______",
        networkId: 3
    };
    var assistInstance = assist.init(bncAssistConfig);

    ABI = [{"constant":true,"inputs":[],"name":"getBalance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"rate","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"withdraw","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_rate","type":"uint256"},{"name":"_validTo","type":"uint256"}],"name":"updateRate","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"isRateValid","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"validTo","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"token","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"_ERC20TokenAddress","type":"address"},{"name":"_rate","type":"uint256"},{"name":"_validTo","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":false,"name":"ETH","type":"uint256"},{"indexed":false,"name":"tokens","type":"uint256"},{"indexed":false,"name":"rate","type":"uint256"}],"name":"Trade","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"rate","type":"uint256"}],"name":"ExchangeRateUpdated","type":"event"}];
    address = "0xd3a4e90defae77874ef95119e3e59c70a741c63d";
    contractRaw = new web3.eth.Contract(ABI, address);
    contract = assistInstance.Contract(contractRaw)

    let validTo = await contract.methods.validTo().call(); $("#validTo").val(validTo);
    
    let rate = await contract.methods.rate().call(); $("#rate").val(rate);

    let network = await web3.eth.net.getId();
    
    function testNetworkTestnetRopsten() {
        if (network !== 3) {
            gotofail();
        }
        
        let networkLongPolling = setInterval(async function(){
            network = await web3.eth.net.getId();
        
            if (network !== 3) {
                clearInterval(networkLongPolling);
                gotofail();
            }
        }, 1000);
    }

    testNetworkTestnetRopsten();

    function gotofail() {
        console.log("WRONG NETWORK");
    }


    $("#send").on("click", function() {
        console.log("ETH: " + $("#eth").val() );


        assistInstance.onboard()
        .then(function(success) {
            console.log("EVERYTHING OK, no action needed");
            // User has been successfully onboarded and is ready to transact
            // This means we can be sure of the follwing user properties:
            //  - They are using a compatible browser
            //  - They have a web3-enabled wallet installed
            //  - The wallet is connected to the config-specified networkId
            //  - The wallet is unlocked and contains at least `minimumBalance` in wei
            //  - They have connected their wallet to the dapp, congruent with EIP1102
        })
        .catch(function(error) {
            // The user exited onboarding before completion
            // Will let you know what stage of onboarding the user was up to when they exited
            console.log(error.message);
        })

    })

})();
```

**Comment by aaronbarnardsound** [comment]
Hey @marsrobertson i believe you are getting that error because you are querying your contract before checking that the user is on the correct network. What you might want to do is structure your app differently so that you don't query your contracts until you have called onboard to make sure that the user is on the correct network. If you don't want to fully onboard the user before querying contracts you could use the `getState` function to check if the user is on the correct network before executing contract queries to avoid errors.

As a side note, since you are using web3 1.0, we recommend passing that in to the `init` call so that `Assist` is using the same version of web3 as you are. You can pass it in by adding it to your config:

```
var bncAssistConfig = {
        dappId: "_____-_______-________-_______",
        networkId: 3,
        web3: web3 // pass in your instantiated version of web3
    };
    var assistInstance = assist.init(bncAssistConfig);
```

Let me know if that helps!

**Comment by aaronbarnardsound** [comment]
@marsrobertson I have created a PR (#163) that adds our "Wrong Network" modal functionality to contract queries when the user is on the wrong network. This should be merged in the next few days (if not sooner). It will now instruct the user to change networks if they are on the wrong network just like in the onboarding flow, but without the rest of the onboarding modals. You will have to handle the rejection/error if the user exits out of the modal which will still require restructuring your app slightly, but the user will at least get some UI feedback if you do try and query a contract when they are on the wrong network.

**Comment by marsrobertson** [comment]
WOW.

Exactly.

That's the thing I had in mind.

Full onboarding: unlocking accoujnt, connecting, permissions, ready to transact.

Basic reading data from smart contract: no need to jump through all the hoops, just check if network is correct.

Now I’m reaching a step further - even if you are on a wrong network, Infura / MetaMask / etc can read data from the correct one?

(not sure if that is technically feasible)

**Comment by aaronbarnardsound** [comment]
This would be possible, but would be a little bit awkward. You would need to spin up another instance of `web3` or `ethers` that has a provider connected to an ethereum node (ie infura) with the network specified to the network your contract is deployed to. You could then create another instance of your contract with that provider. You can then query this contract without having to worry about which network the user is on as it is no longer dependent on the MetaMask provider. Hope that helps mate!

**Comment by marsrobertson** [comment]
It is awkward, I know.

It is still possible though.

1. Ability to browse the Dapp, displaying everything, checking things out (separate provider)

2. Actually transacting with the contract, here you need to select the right network

It's too much hassle, too much burden for me, so many other, more important issues.

However, if you believe that it is a usability improvement and your company stands for usability, adoption and user onboarding then you may do a quick show of hands / market research.

**RANDOM:** Me using BlockNative Assist on Ropsten: https://genesis.re/trustless-token-transfer-trade/
