### ISSUE TITLE
Assist notification when web3.eth.sendTransaction to send ETH to fallback function?

### ISSUE THREAD

**Issue by marsrobertson** [blocknative/assist#164]
I'm not calling contract method.

I'm just sending ETH to contract address.

Maybe display notifications too?

---

I'd like to call the callback function to get nice messages, but not sure how: https://ethereum.stackexchange.com/questions/16616/how-to-trigger-contract-fallback-function-from-javascript

Here they suggest just `sendTransaction` 🤷‍♂️

**Comment by morelazers** [comment]
I think this can be achieved with `assist.Transaction()` but I'll let @aaronbarnardsound chime in.

https://github.com/blocknative/assist#transactiontxobject--callback

**Comment by aaronbarnardsound** [comment]
Yes @morelazers is correct. You can use `assist.Transaction(txOptions)` to send a transaction. `txOptions` is a JavaScript object that you would include `to` and `value` properties:
```
assist.Transaction({
  to:  // the address of the contract you want to send value to,
  value: // the value in `wei` that you would like to send
})
```

**Comment by marsrobertson** [comment]
Thank you!
