### ISSUE TITLE
Custom timeout doesn't work to assist.notify

### ISSUE THREAD

**Issue by morelazers** [blocknative/assist#194]
Always dismisses after 5 seconds.

**Comment by liamaharon** [comment]
I'm unable to reproduce this. Can you link a repo with the issue?

**Comment by morelazers** [comment]
https://github.com/MostlyUnemployed/C.R.E.A.M

Apologies for shitty code.

`yarn && yarn start` should work, set your metamask to mainnet, start a tx and then watch the notification disappear.

Code is in `utils/wallet/index.js`

**Comment by liamaharon** [comment]
Resolved with @morelazers offline, the project was using a pre-release version of the notify API
