### ISSUE TITLE
Widget thinks my metamask is set to local

### ISSUE THREAD

**Issue by hshar7** [blocknative/assist#23]
The widget keeps on thinking that metamask is not on the network that I selected (4 -> rinkeby)
Take a look at image
![screenshot from 2019-02-15 17-31-08](https://user-images.githubusercontent.com/17727543/52890014-351cd880-3148-11e9-8027-17083a661a39.png)

**Comment by cmeisl** [comment]
@hshar7 Thank you for the issue report. We are looking into the problem right now.

**Comment by hshar7** [comment]
The simple code that I'm using:
`
import React, { Component } from 'react';
import './App.css';
import assist from 'bnc-assist';

class App extends Component {

  componentWillMount() {
    let bncAssistConfig = {
      dappId: 'xxx',
      networkId: 4
    };

    let assistInstance = assist.init(bncAssistConfig);

    assistInstance.onboard()
        .then(success => {
          console.log('success');
          console.log(success);
        })
        .catch(error => {
          console.log('error');
          console.log(error);
        })
  }

  render() {
    return (
      <div className="App">
        <p>hi</p>
      </div>
    );
  }
}

export default App;

`

**Comment by cmeisl** [comment]
@hshar7 We updated the npm build to 0.3.2 to fix this issue. Please update you project to use bnc-assist 0.3.2 and let us know if the issue is fixed for you.

You code sample looks great.

**Comment by hshar7** [comment]
thanks
