### ISSUE TITLE
Modal dialog does not disappear if notification follows right after

### ISSUE THREAD

**Issue by spape** [blocknative/assist#261]
👋 gu.cards here

I would like to report the following bug:

<img width="1680" alt="Screen Shot 2019-06-06 at 9 55 08 PM" src="https://user-images.githubusercontent.com/851393/59062526-585dc600-88a6-11e9-89a5-f96d74a198bf.png">
<img width="1680" alt="Screen Shot 2019-06-06 at 9 55 14 PM" src="https://user-images.githubusercontent.com/851393/59062530-5b58b680-88a6-11e9-8aaf-e754d1e7b629.png">
<img width="1680" alt="Screen Shot 2019-06-06 at 9 55 19 PM" src="https://user-images.githubusercontent.com/851393/59062537-5f84d400-88a6-11e9-8aa6-78fe9a8dd134.png">
<img width="1680" alt="Screen Shot 2019-06-06 at 9 55 25 PM" src="https://user-images.githubusercontent.com/851393/59062546-63185b00-88a6-11e9-868d-f6f0b9edfc80.png">
<img width="1680" alt="Screen Shot 2019-06-06 at 9 57 32 PM" src="https://user-images.githubusercontent.com/851393/59062550-657ab500-88a6-11e9-8fb3-54282c47a446.png">
<img width="1680" alt="Screen Shot 2019-06-06 at 9 57 40 PM" src="https://user-images.githubusercontent.com/851393/59062554-6875a580-88a6-11e9-9733-4432fc4548fd.png">

Steps to reproduce:
- Be on the wrong network
- Trigger the wallet check
- Change to the right network
- Have insufficient funds on your account of the new network
- Click "Check my network"

Perceived behaviour:
- Modal does not disappear, but the whole iframe integration moves to the side (as it tries to show the "insufficient funds" notification)

Expected behaviour:
- Modal should disappear completely, and I should just see the "insufficient funds" notification

**Comment by cmeisl** [comment]
@spape thank you for the bug report. Which version of Assist are you using?

**Comment by aaronbarnardsound** [comment]
@spape Does the window reload for you when you change network?

**Comment by spape** [comment]
@aaronbarnardsound no it does not reload when I switch network in Metamask

**Comment by spape** [comment]
@aaronbarnardsound it's live now, and you can test it yourself here: 

https://gu.cards/tournament-tickets

- be on the wrong network (e.g. ropsten) before you start
- you need to have a wide screen... seems to work for <= ~1200px
