### ISSUE TITLE
Separate stall events for pending and confirmed

### ISSUE THREAD

**Issue by cmeisl** [blocknative/assist#278]
Separate the `txStall` event into one for stalled getting to a pending state (i.e. tx never seen in mempool) and one for stalled getting confirmed. Stalled getting to pending can have a shorter timeout. Stalled getting to confirmed can have a longer timeout, especially on mainnet.

https://github.com/blocknative/assist/blob/21f067e126d91a75183c35c9ceb21b6dff5db3fd/src/js/logic/send-transaction.js#L284

Need to consider how to handle stall notifications if backend nodes are not syncing and therefore not able to see mempool or make new block queries.

Also consider compatibility with current `txStall` for existing data.

**Comment by aaronbarnardsound** [comment]
Closed by afbf565dda006158f6f1397d8ea645fa6d307eff
