### ISSUE TITLE
Investigate Web3.js and Ethers.js integrations

### ISSUE THREAD

**Issue by morelazers** [blocknative/assist#28]
Web3js upwards of 1.0-beta37 is currently broken.

Investigate wrapping Ethers.js such that we can use a small, locked down blockchain interaction library in our implementation.

**Comment by cmeisl** [comment]
https://docs.google.com/document/d/1uNpjnYAx_rTT3pki0SwhKIIjJe02wNIFUGTL4KzSeZY

**Comment by marsrobertson** [comment]
I'm currently using Ethers.js

I was checking if you plan to support it...

**Comment by cmeisl** [comment]
@marsrobertson Yes, we are evaluating support for ethers.js (we really like ethers.js!). Will notify you as soon as we have a sense of timing.
