### ISSUE TITLE
Contract call transaction does not reject properly for promiEvents

### ISSUE THREAD

**Issue by sterlu** [blocknative/assist#329]
Related to #280/#281 

When sending a contract method call tx, failing doesn't cause the promiEvent to reject. If I reject the transaction on Metamask for example, this never throws:
```js
const ctx = bcn.Contract(contract);
await ctx.methods[contractFunc](...funcParams).send(txParams)
```
Replacing it with the following causes it to work correctly:
```js
const ctx = bcn.Contract(contract);
await new Promise((res, rej) => {
  ctx.methods[contractFunc](...funcParams).send(txParams, (err, hash) => 
    (err ? rej(err) : res(hash)));
});
```

Seems to me that `promiEvent` is missing in js/logic/send-transaction.js lines 219, 233 and 259.

**Comment by aaronbarnardsound** [comment]
Yo @sterlu, what version of Assist are you using?

**Comment by aaronbarnardsound** [comment]
and also which version of web3.js?

**Comment by sterlu** [comment]
@aaronbarnardsound Assist v0.9.2 & Web3 v1.0.0-beta.55

**Comment by aaronbarnardsound** [comment]
Sweet thanks. Have found where the bug is and we'll have a PR created soon to have this fixed 👍
