### ISSUE TITLE
Change `readme.md` to reflect issues with versions of `web3.js`

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/assist#35]
Some `web3.js` versions have bugs/errors when interacting with MetaMask and `assist` reflects these errors.
Bugs exist on these versions:

`beta-38`
`beta-39`
`beta-40`
`beta-41`
`beta-43`
`beta-44`

Docs need to be updated to reflect this.

**Comment by cmeisl** [comment]
included in 0.4.0 release with commit 003cc0bb77a20cd5038b1a4cdea5a9885181027a
