### ISSUE TITLE
truffle contracts broken in create-react-app builds

### ISSUE THREAD

**Issue by liamaharon** [blocknative/assist#354]

**Comment by liamaharon** [comment]
create-react-app uses terser.js default settings when building assist. 

The default settings uglifies Class names, causing https://github.com/blocknative/assist/blob/458417ffdb9824d792eab5b609955fb67ab10fe7/src/js/index.js#L271 to always evaluate to false.

I see two options on how we could proceed here:
1. add documentation mentioning if you use terser.js or uglify.js to set `keep_fnames` to `true` (see https://github.com/terser-js/terser#minify-options)
2. find a different way of differentiating truffle contracts and web3.js contracts that doesn't rely on `contructor.name`.

@aaronbarnardsound @cmeisl what are your thoughts?

**Comment by liamaharon** [comment]
Implementing option 1 for now.

**Comment by aaronbarnardsound** [comment]
Closed by afbf565dda006158f6f1397d8ea645fa6d307eff
