### ISSUE TITLE
assist is is incompatible with new >1.0 / 2.0-alpha web3.js versions

### ISSUE THREAD

**Issue by liamaharon** [blocknative/assist#355]
https://medium.com/@samuel_91690/1-0-release-web3-js-ddd23d3c8f62

1.0.0-beta.37 --> v1.0
1.0.0-beta.38 --> v2.0-alpha

and they're making minor version releases (eg v1.1, v1.2) which don't work in assist.js as it is right now. I don't think it would be too much work to add support (:crossed_fingers:).

**Comment by aaronbarnardsound** [comment]
Closed by afbf565dda006158f6f1397d8ea645fa6d307eff
