### ISSUE TITLE
configurable browser check

### ISSUE THREAD

**Issue by cmeisl** [blocknative/assist#374]
Add `checkBrowser` config field with a default value of `true` for backwards compatibility. If set to `false`, the browser check feature of on-boarding (i.e. detect if browser supports MM extension) is bypassed. This applies to mobile as well.

This feature is to support wallets that work in Safari and non-wallet browsers on mobile due to using SDK wallets and/or hardware wallets.

**Comment by aaronbarnardsound** [comment]
Closed via #375
