### ISSUE TITLE
web3 1.0.0-beta-36 doesn't fire 'receipt' event

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/assist#42]
`assist.js` utilizes it's own Ethereum node on the backend to monitor transaction status, but in the case of our node failing we fall back to using Infura's node by listening for the receipt event fired on the `promiEvent` in `web3.js`.

```
txPromise.on('receipt', txReceipt => {
// handle the txReceipt here
})
```

When using `web3 1.0.0-beta-36`, the `'receipt'` event doesn't fire. This means that if in the case that our node is not functioning correctly, `assist.js` will inform the user that the transaction has stalled when it has actually been confirmed. 

This issue was fixed in `web3 1.0.0-beta-37`. We can update our documentation to include `web3 1.0.0-beta-36` as a version that we recommend developers don't use with `assist.js`, or at least warn that `assist.js` will not function as expected if our node happens to be not functioning correctly.

**Comment by cmeisl** [comment]
No action required.
