### ISSUE TITLE
Set corner for transaction support notifications

### ISSUE THREAD

**Issue by cmeisl** [blocknative/assist#70]
Notification toasters currently appear in lower left corner of the browser window, stacking upwards. Allow Dapp to choose which corner to use. Top left/right corner would stack downwards. Bottom left/right corners would stack upwards.

**Comment by aaronbarnardsound** [comment]
@cmeisl Are you thinking that the Blocknative logo will be inverted as well when the toasters are set to top left/right? So the logo would be on top with toasters stacking downwards underneath it making a mirror image of the current notifications setup.

**Comment by aaronbarnardsound** [comment]
Closed via #81
