### ISSUE TITLE
Cannot read sufficientBalance of undefined

### ISSUE THREAD

**Issue by hshar7** [blocknative/assist#84]
I get error Cannot read sufficientBalance of undefined when I try to transact with decorated smart contract.
Regular contract is able to execute the transaction successfully with the same arguments.
I'm using "web3": "0.20.6" and "bnc-assist": "0.5.0"

**Comment by aaronbarnardsound** [comment]
@hshar7 I believe we fixed this in version `0.5.1`. We are in the process of publishing that version to NPM currently. Until then you could try pulling down the repo and creating a build from the `develop` branch and using that instead. I will update you here once NPM has been updated with the new version.

**Comment by cmeisl** [comment]
@hshar7 Version `0.5.1` is up. Checkout release notes here: https://github.com/blocknative/assist/releases/tag/0.5.1

If this version does not resolve your issue, please let us know so we can investigate further.

**Comment by hshar7** [comment]
Thanks seems like it's been fixed with the new version.
Really quick turnaround :)

**Comment by cmeisl** [comment]
Well, we had a little regression in `0.5.1` that could break on-boarding, so recommend going with just released `0.5.2`
